spring.application.name={{ project_name | lower }}
{% if spring_has_data_jpa or spring_has_batch %}
{% if spring_has_postgresql %}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/{{ project_name }}}
spring.datasource.username=${DATABASE_USER:app}
spring.datasource.password=${DATABASE_PASSWORD:local-dev}
{% else %}
spring.datasource.url=jdbc:h2:mem:application;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
{% endif %}
{% if spring_has_data_jpa %}
spring.jpa.hibernate.ddl-auto=update
{% endif %}
{% if spring_has_batch %}
spring.batch.jdbc.initialize-schema=always
{% endif %}
{% endif %}
